language: java
sudo: required
jdk: openjdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean install

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

deploy:
  provider: script
  script: docker push microportal/portal-app2-service
  on:
    branch: master